// LOCALHOST
### Get all To Do list items
GET http://localhost:8080/todo/
### Create To Do list item
POST http://localhost:8080/todo/ HTTP/1.1
# apiKey: <insert apiKey>
Content-Type: application/json
# Authorization: Bearer <insert JWT from callback/payload/viewsourcehere>

{
    "listItem": "Make To Do List",
}
### PUT todo item
PUT http://localhost:8080/todo/ HTTP/1.1
content-type: application/json

{
    "listItem": "Finish project"
}
### DELETE list item
DELETE http://localhost:8080/todo/ HTTP/1.1

// Render
### Get all To Do list items
GET http://chrisleavitt5.onrender.com/todo/
### Create To Do list item
POST http://chrisleavitt5.onrender.com/todo/ HTTP/1.1
# apiKey: <insert apiKey>
Content-Type: application/json
# Authorization: Bearer <insert JWT from callback/payload/viewsourcehere>

{
    "listItem": "Make To Do List",
}
### PUT todo item
PUT http://chrisleavitt5.onrender.com/todo/ HTTP/1.1
content-type: application/json

{
    "listItem": "Finish project"
}
### DELETE list item
DELETE http://chrisleavitt5.onrender.com/todo/ HTTP/1.1